project_id = "card-gacha-renewal"

[functions.game-command]
verify_jwt = false

[functions.session-exchange]
verify_jwt = false

[functions.soop-bridge]
verify_jwt = false

[functions.soop-auth]
verify_jwt = false

[functions.fix-anon-grant]
enabled = true
verify_jwt = false
import_map = "./functions/fix-anon-grant/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fix-anon-grant/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fix-anon-grant/*.html" ]
